spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddorang?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: your-password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: your-secret-key
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000
